### ISSUE TITLE
Text scaling in schematics is broken in the PDF

### ISSUE THREAD

**Issue by michaelk99** [iic-jku/analog-circuit-design#4]
The scale and placement of port and circuit component labels is wrong in the PDF.

## Example

![image](https://github.com/user-attachments/assets/f1044b74-553b-4685-9683-c6a437384b52)

**Comment by hpretl** [comment]
Solved! :-) One has to add `sd.svgconfig.svg2 = False` to make it work. I will now rework all the schematics.
